apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-order-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customer-order-service
  template:
    metadata:
      labels:
        app: customer-order-service
    spec:
      containers:
        - name: customer-order-service
          image: your-docker-image:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: customer-order-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: customer-order-service